<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="1" total="9" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="56349" started-at="2022-09-05T17:45:58Z" finished-at="2022-09-05T17:46:55Z">
    <groups>
      <group name="fruit">
        <method signature="Logintestng.tc3()[pri:-5, instance:org.testng.Logintestng@5c3bd550]" name="tc3" class="org.testng.Logintestng"/>
      </group> <!-- fruit -->
      <group name="smoke">
        <method signature="Logintestng.tc3()[pri:-5, instance:org.testng.Logintestng@5c3bd550]" name="tc3" class="org.testng.Logintestng"/>
        <method signature="Logintestng.tc4()[pri:5, instance:org.testng.Logintestng@5c3bd550]" name="tc4" class="org.testng.Logintestng"/>
        <method signature="Logintestng.tc5()[pri:4, instance:org.testng.Logintestng@5c3bd550]" name="tc5" class="org.testng.Logintestng"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="Logintestng.tc1()[pri:-2, instance:org.testng.Logintestng@5c3bd550]" name="tc1" class="org.testng.Logintestng"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Test" duration-ms="56349" started-at="2022-09-05T17:45:58Z" finished-at="2022-09-05T17:46:55Z">
      <class name="org.testng.Logintestng">
        <test-method status="PASS" signature="browser()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="browser" is-config="true" duration-ms="4242" started-at="2022-09-05T17:45:58Z" finished-at="2022-09-05T17:46:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="5747" started-at="2022-09-05T17:46:03Z" finished-at="2022-09-05T17:46:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="tc3()[pri:-5, instance:org.testng.Logintestng@5c3bd550]" name="tc3" duration-ms="5382" started-at="2022-09-05T17:46:09Z" finished-at="2022-09-05T17:46:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="1" started-at="2022-09-05T17:46:14Z" finished-at="2022-09-05T17:46:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="2748" started-at="2022-09-05T17:46:14Z" finished-at="2022-09-05T17:46:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="tc3()[pri:-5, instance:org.testng.Logintestng@5c3bd550]" name="tc3" duration-ms="4992" started-at="2022-09-05T17:46:17Z" finished-at="2022-09-05T17:46:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="0" started-at="2022-09-05T17:46:22Z" finished-at="2022-09-05T17:46:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="1711" started-at="2022-09-05T17:46:22Z" finished-at="2022-09-05T17:46:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="tc1()[pri:-2, instance:org.testng.Logintestng@5c3bd550]" name="tc1" duration-ms="5033" started-at="2022-09-05T17:46:23Z" finished-at="2022-09-05T17:46:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="1" started-at="2022-09-05T17:46:28Z" finished-at="2022-09-05T17:46:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="2561" started-at="2022-09-05T17:46:28Z" finished-at="2022-09-05T17:46:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="tc5()[pri:4, instance:org.testng.Logintestng@5c3bd550]" name="tc5" duration-ms="2803" started-at="2022-09-05T17:46:31Z" finished-at="2022-09-05T17:46:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Logintestng.tc5(Logintestng.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="0" started-at="2022-09-05T17:46:34Z" finished-at="2022-09-05T17:46:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="3023" started-at="2022-09-05T17:46:34Z" finished-at="2022-09-05T17:46:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="tc5()[pri:4, instance:org.testng.Logintestng@5c3bd550]" name="tc5" duration-ms="1975" started-at="2022-09-05T17:46:37Z" finished-at="2022-09-05T17:46:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Logintestng.tc5(Logintestng.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="0" started-at="2022-09-05T17:46:39Z" finished-at="2022-09-05T17:46:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="2486" started-at="2022-09-05T17:46:39Z" finished-at="2022-09-05T17:46:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="tc5()[pri:4, instance:org.testng.Logintestng@5c3bd550]" name="tc5" duration-ms="2641" started-at="2022-09-05T17:46:41Z" finished-at="2022-09-05T17:46:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Logintestng.tc5(Logintestng.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="0" started-at="2022-09-05T17:46:44Z" finished-at="2022-09-05T17:46:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="2257" started-at="2022-09-05T17:46:44Z" finished-at="2022-09-05T17:46:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="tc5()[pri:4, instance:org.testng.Logintestng@5c3bd550]" name="tc5" duration-ms="2428" started-at="2022-09-05T17:46:46Z" finished-at="2022-09-05T17:46:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Logintestng.tc5(Logintestng.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc5 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="1" started-at="2022-09-05T17:46:49Z" finished-at="2022-09-05T17:46:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="start" is-config="true" duration-ms="1581" started-at="2022-09-05T17:46:49Z" finished-at="2022-09-05T17:46:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="tc4()[pri:5, instance:org.testng.Logintestng@5c3bd550]" name="tc4" duration-ms="4308" started-at="2022-09-05T17:46:50Z" finished-at="2022-09-05T17:46:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc4 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="end" is-config="true" duration-ms="1" started-at="2022-09-05T17:46:54Z" finished-at="2022-09-05T17:46:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="browserclose()[pri:0, instance:org.testng.Logintestng@5c3bd550]" name="browserclose" is-config="true" duration-ms="335" started-at="2022-09-05T17:46:54Z" finished-at="2022-09-05T17:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserclose -->
      </class> <!-- org.testng.Logintestng -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
